### ISSUE TITLE
No Auth Provider found for name "gcp"

### ISSUE THREAD

**Issue by wrdls** [nuvo/orca#11]
Wanted to try this tool but it doesn't seem to work with a kubeconfig with a gcp auth-provider. My user looks like this:
```
- name: gke-cluster
  user:
    auth-provider:
      config:
        access-token: <token>
        cmd-args: config config-helper --format=json
        cmd-path: /opt/google-cloud-sdk/bin/gcloud
        expiry: "2019-01-08T12:48:04Z"
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
```
Found this possibly related issue: https://github.com/kubernetes/client-go/issues/242
